import { weekAgo } from "../lib/date.js";
import type { DigestConfig } from "../types/digest.js";

const sources: string[] = [
    "http://antonz.ru/rss/",
    "http://bizikov.ru/posts/feed/",
    "http://glebkalinin.ru/atom.xml",
    "http://ilyabirman.ru/meanwhile/rss/",
    "http://nano.sapegin.ru/atom.xml",
    "http://softwaremaniacs.org/blog/feed/",
    "http://vsevolodustinov.ru/blog/rss/",
    "https://9dots.ru/feed/",
    "https://a11y-blog.dev/ru/feed.xml",
    "https://addyosmani.com/feed.xml",
    "https://arturpaikin.com/ru/blog-feed.xml",
    "https://bespoyasov.ru/rss.xml",
    "https://blog.logrocket.com/feed/",
    "https://bolknote.ru/rss/",
    "https://brucelawson.co.uk/feed/",
    "https://chromereleases.googleblog.com/feeds/posts/default",
    "https://css-tricks.com/feed",
    "https://danis.one/rss/",
    "https://dxdt.ru/feed/",
    "https://feeds.feedburner.com/kizuruen",
    "https://forweb.dev/ru/blog/feed.xml",
    "https://github.blog/changelog/feed/",
    "https://github.blog/feed/",
    "https://kentcdodds.com/blog/rss.xml",
    "https://ksoftware.livejournal.com/data/atom",
    "https://lea.verou.me/feed.xml",
    "https://losko.ru/feed/",
    "https://mikeozornin.ru/blog/rss/",
    "https://p.umputun.com/index.xml",
    "https://powerwill.ru/index.xml",
    "https://rakhim.exotext.com/rss.xml",
    "https://ru.hexlet.io/blog.rss",
    "https://sapegin.me/atom.xml",
    "https://sergeykorol.ru/blog/feed/",
    "https://smashingmagazine.com/feed",
    "https://svelte.dev/blog/rss.xml",
    "https://timmarinin.net/notes/feed.rss",
    "https://tonsky.me/atom.xml",
    "https://vorushin.github.io/feed.xml",
    "https://vsevolodustinov.ru/blog/rss/",
    "https://www.developerway.com/rss.xml",
];

export const personalWeekly: DigestConfig = {
    sources,
    title: "Personal Weekly",
    path: "personal/weekly",
    since: weekAgo,
};
